worlds = ['Jap', 'China', 'London', 'Tokyo', 'Beijing']
print(worlds)
print(sorted(worlds))
print(worlds)
print(sorted(worlds,reverse=True))
print(worlds)
worlds.reverse()
print(worlds)
worlds.reverse()
print(worlds)
worlds.sort()
print(worlds)
worlds.sort(reverse=True)
print(worlds)
print(len(worlds))